config/routes.rb
Rails.application.routes.draw do
  root 'people#index'
  resources :people
  resources :albums
end

app/models/ability.rb
class Ability < ApplicationRecord
  AbilityNameList = %i(ability1 ability2 ability3)

  belongs_to :person
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :person

  validates :kind, presence: true
  validates :street, presence: true
end

app/models/album.rb
class Album < ApplicationRecord
  has_one :artist, dependent: :destroy
  has_many :songs, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :album
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :abilities, dependent: :destroy
  accepts_nested_attributes_for :addresses, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :abilities, allow_destroy: true, reject_if: :all_blank

  validates :first_name, presence: true
  validates :last_name, presence: true

  # personが持っている各Abilityのインスタンスに対して、以下のキーと値から成る
  # Hashをかえす
  #   キー : ability_nameをシンボル化したもの
  #   値 : Abilityのインスタンス
  # @return [Hash] キーはability_nameのシンボル、値はAbilityのインスタンス
  def ability_selections
    abilities.map do |record|
      [record.ability_name.to_sym, record]
    end.to_h
  end

  # データが存在しており、かつ削除対象となっていない（marked_for_destruction?がfalse）
  # である場合はtrueを、それ以外はfalseを返す。
  # @param ability_name [Symbol] 対象のability名
  # @return [Boolean] データが存在し、削除対象となっていない場合はtrue、それ以外はfalse
  def checked?(ability_name)
    ability_selection = ability_selections[ability_name.to_sym]
    ability_selection.present? && !ability_selection.marked_for_destruction?
  end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def new
    album = Album.new
    # artistとsongの入力フォームを生成する
    album.build_artist
    album.songs.build
    @form = AlbumForm.new(album)
  end

  def create
    album = Album.new
    @form = AlbumForm.new(album)
    if @form.validate(album_params)
      @form.save
      redirect_to albums_path, notice: 'アルバムを作成しました'
    else
      render :new
    end
  end

  def edit
    @form = AlbumForm.new(Album.find(params[:id]))
  end

  def update
    @form = AlbumForm.new(Album.find(params[:id]))
    if @form.validate(album_params)
      @form.save
      redirect_to albums_path, notice: 'アルバムを更新しました'
    else
      render :edit
    end
  end

  def show
    @album = Album.find(params[:id])
  end

  def destroy
    Album.find(params[:id]).destroy
    redirect_to albums_path, notice: 'アルバムを削除しました'
  end

  private
  def album_params
    params.require(:album).permit(:album_title,
                                  artist_attributes: [:id, :full_name],
                                  songs_attributes: [:id, :title, :_destroy]
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to @person, notice: "#{@person.last_name} #{@person.first_name}を作成しました"
    else
      render 'new'
    end
  end

  def show
    @person = Person.find(params[:id])
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to @person, notice: "#{@person.last_name} #{@person.first_name}を更新しました"
    else
      render 'edit'
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_path, notice: "#{@person.last_name} #{@person.first_name}を削除しました"
  end

  private
  def person_params
    # チェックされていない場合は:ability_nameが空となっている。その時は
    # 削除対象とする
    params[:person][:abilities_attributes].each do |_i, hash|
      hash[:_destroy] = hash[:ability_name].blank?
    end
    params.require(:person).permit(:first_name, :last_name,
                                   addresses_attributes: [:id, :kind, :street, :_destroy],
                                   abilities_attributes: [:id, :ability_name, :_destroy]
                                   )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # fと関連付けられたassociationのフォームを作成し、data属性に生成したHTMLデータを格納した
  # リンクを生成して呼び出し元にかえす。実際これを使うにはapp/javascript/packs/nested-form/addFields.js
  # にてフォームを画面としてレンダリングさせる処理を実施する必要がある
  def link_to_add_fields(name, f, association)
    new_obj = f.object.send(association).klass.new
    # idは一意であれば何でもよい。
    id = new_obj.object_id

    fields = f.fields_for(association, new_obj, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end

    link_to(name, '#', class: 'add_fields btn btn-primary', data: {id: id, fields: fields.gsub('\n', '')})
  end
end

app/helpers/person_helper.rb
module PersonHelper
  # Personモデルと1対多の関係にあるAbilityモデルに対してaccepts_nested_attributes_forとして
  # 指定した際に生成されるname属性の文字列を返す。
  # @param [Integer] index フォーム内で一意となる番号
  # @return [String] "person[abilities_attributes][" + index + "]"
  def ability_name_prefix(index)
    "person[abilities_attributes][#{index}]"
  end

  # Personモデルと1対多の関係にあるAbilityモデルに対してaccepts_nested_attributes_forとして
  # 指定した際に生成されるid属性の文字列を返す。
  # @param [Integer] index フォーム内で一意となる番号
  # @return [String] "person_abilities_attributes_" + index
  def ability_id_prefix(index)
    "person_abilities_attributes_#{index}"
  end

  # すでに登録されているAbilityのidを値に持つhiddenタグを作成する
  # @param [Integer] index フォーム内で一意となる番号
  # @param [Symbol] ability_name AbilityName
  # @param [Person] person Abilityに紐づくPersonのインスタンス
  # @return [String] 作成したhiddenタグのHTML
  def ability_hidden_tag(index, ability_name, person)
    record = person.ability_selections[ability_name]
    tag.input type: 'hidden',
              id: "#{ability_id_prefix(index)}_id",
              name: "#{ability_name_prefix(index)}[id]",
              value: record.try(:id)
  end

  # Abilityが取りうるAbilityNameに対応したチェックボックスを作成する
  # すでにチェックされているものに対してはチェックを入れる。
  # @param [Integer] index フォーム内で一意となる番号
  # @param [Symbol] ability_name AbilityName
  # @param [Person] person Abilityに紐づくPersonのインスタンス
  # @return [String] 作成したチェックボックスのHTML
  def ability_checkbox_tag(index, ability_name, person)
    tag.input type: 'checkbox',
              id: "#{ability_id_prefix(index)}_ability_name",
              name: "#{ability_name_prefix(index)}[ability_name]",
              value: ability_name,
              checked: person.checked?(ability_name)
  end

  # Abilityが取りうるAbilityNameを登録するためのチェックボックスやラベルなどを作成する
  # すでにチェックされているものに対してはチェックを入れる。
  # @param [Integer] index フォーム内で一意となる番号
  # @param [Symbol] ability_name AbilityName
  # @param [Person] person Abilityに紐づくPersonのインスタンス
  # @return [String] 作成したチェックボックスやラベルなどのHTML
  def ability_form(index, ability_name, person)
    tag.label class: 'form-check-label' do
      ability_hidden_tag(index, ability_name, person) + ability_checkbox_tag(index, ability_name, person)+ "#{ability_name}"
    end
  end
end

app/views/albums/_form.html.erb
<%= form_with(model: @form, local: true) do |f| %>
  <%= render 'shared/validation-messages', object: @form %>
  <div class="form-group">
    <%= f.label :album_title %>
    <%= f.text_field :album_title, class: 'form-control' %>
  </div>

  <fieldset>
    <legend>Artist:</legend>
    <%= f.fields_for :artist do |artist_form| %>
      <%= artist_form.label :full_name %>
      <%= artist_form.text_field :full_name, class: 'form-control' %>
    <% end %>
  </fieldset>

  <fieldset>
    <legend>Songs:</legend>
    <div data-controller="nested-form">
      <template id="song_fields_template">
        <%= f.fields_for :songs, Song.new, child_index: 'NEW_RECORD' do |song_form| %>
          <%= render "song_fields", form: song_form %>
        <% end %>
      </template>
    </div>
    <%= f.fields_for :songs do |song_form| %>
      <%= render "song_fields", form: song_form %>
    <% end %>
    <%= link_to('追加', '#', class: 'btn btn-primary add_album_fields') %>
  </fieldset>
  <%= f.submit class: 'btn btn-primary mt-2' %>
<% end %>

app/views/albums/_song_fields.html.erb
<%= content_tag :div, class: "nested-fields", data: { new_record: form.object.new_record? } do %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
    <%= form.hidden_field :_destroy %>
    <%= link_to '削除', '#', class: 'btn btn-danger remove_song_fields' %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>アルバムを編集</h1>
<%= render 'form' %>

app/views/albums/index.html.erb
<h1>Albums</h1>

<table class="table">
  <thead>
  <tr>
    <td>Album Title</td>
    <td colspan="3">Links</td>
  </tr>
  </thead>
  <tbody>
  <% @albums.each do |album| %>
    <tr>
      <td><%= album.album_title %></td>
      <td><%= link_to('詳細', album_path(album), class: 'btn btn-primary') %></td>
      <td><%= link_to('編集', edit_album_path(album), class: 'btn btn-secondary') %></td>
      <td><%= link_to('削除', album_path(album), class: 'btn btn-danger', method: :delete, data: { confirm: '削除しますか?'}) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to '新規作成', new_album_path, class: 'btn btn-primary' %>

app/views/albums/new.html.erb
<h1>新しいアルバムを追加</h1>
<%= render 'form' %>

app/views/albums/show.html.erb
<h1>Album <%= @album.album_title %> detail</h1>
<h2>Artist is <%= @album.artist.full_name %></h2>
<% if @album.songs.any? %>
  <h2>Songs:</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
      </tr>
    </thead>
    <tbody>
      <% @album.songs.each do |song| %>
        <tr>
          <td><%= song.title %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'アルバム一覧', albums_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/people/_address_fields.html.erb
<div class='nested-fields form-row'>
  <%= f.hidden_field :_destroy %>
  <div class='form-group col-sm-4'>
    <%= f.label :kind %>
    <%= f.text_field :kind, class: 'form-control' %>
  </div>
  <div class='form-group col-sm-4'>
    <%= f.label :street %>
    <%= f.text_field :street, class: 'form-control' %>
  </div>
  <div>
    <%= link_to '削除', '#', class: 'remove_fields btn btn-danger' %>
  </div>
</div>

app/views/people/_form.html.erb
<%= form_with(model: @person, local: true) do |f| %>
  <%= render 'shared/validation-messages', object: @person %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>

  <fieldset>
    <legend>Addresses:</legend>
    <%= f.fields_for :addresses do |addresses_form| %>
      <%= render 'address_fields', f: addresses_form %>
    <% end %>
    <%= link_to_add_fields '住所の追加', f, :addresses %>
  </fieldset>

  <fieldset>
    <legend>Abilities</legend>
    <div class="form-check form-check-inline">
      <% Ability::AbilityNameList.each_with_index do |ability_name, index| %>
        <%= ability_form(index, ability_name, @person) %>
      <% end %>
    </div>
  </fieldset>
  <%= f.submit class: 'btn btn-primary mt-2' %>
<% end %>

app/views/people/edit.html.erb
<h1>編集 <%= @person.first_name %> <%= @person.last_name %></h1>
<%= render "form" %>

app/views/people/index.html.erb
<h1>People</h1>

<table class="table">
  <thead>
    <tr>
      <td>First Name</td>
      <td>Last Name</td>
      <td colspan="3">Links</td>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= link_to('詳細', person_path(person), class: 'btn btn-primary') %></td>
        <td><%= link_to('編集', edit_person_path(person), class: 'btn btn-secondary') %></td>
        <td><%= link_to('削除', person_path(person), class: 'btn btn-danger', method: :delete, data: { confirm: '削除しますか?'}) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '新規作成', new_person_path, class: 'btn btn-primary' %>

app/views/people/new.html.erb
<h1>新しい人を追加</h1>
<%= render 'form' %>

app/views/people/show.html.erb
<h1><%= @person.first_name %> <%= @person.last_name %></h1>
<% if @person.addresses.any? %>
  <h2>Addresses:</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Kind</th>
        <th>Street</th>
      </tr>
    </thead>
    <tbody>
      <% @person.addresses.each do |address| %>
        <tr>
          <td><%= address.kind %></td>
          <td><%= address.street %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<% if @person.abilities.any? %>
  <h2>Ability</h2>
  <ul>
    <% @person.abilities.each do |ability| %>
      <li>
        <%= ability.ability_name %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= link_to '一覧', people_path, class: 'btn btn-primary' %>

app/views/shared/_validation-messages.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <p>入力されたフォームにエラーがあります。</p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>